export const LOAD_START_INGREDIENTS_DATA ='LOAD_START_INGREDIENTS_DATA';
export const LOAD_START_INGREDIENTS_DATA_REQUEST = 'LOAD_START_INGREDIENTS_DATA_REQUEST';
export const LOAD_START_INGREDIENTS_DATA_SUCCES = 'LOAD_START_INGREDIENTS_DATA_SUCCES';
export const LOAD_START_INGREDIENTS_DATA_FAILED = 'LOAD_START_INGREDIENTS_DATA_FAILED';


